In [1]:
import pandas as pd
from sklearn import linear_model
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import Lasso
from sklearn import metrics
import numpy as np

import warnings

warnings.filterwarnings('ignore');


In [2]:
df = pd.read_csv("DataBase_WeatherRentalAmount_UTC.csv", index_col='FormattedDate')

In [3]:
df.head()

Temperature  TotalCloudCover  PrecipitationHeight  \
FormattedDate                                                            
2014-12-31 23:00:00          1.2                8                  0.0   
2015-01-01 00:00:00          1.2                8                  0.0   
2015-01-01 01:00:00          1.1                8                  0.0   
2015-01-01 02:00:00          1.2               -1                  0.0   
2015-01-01 03:00:00          1.1               -1                  0.0   

                     MeanWindSpeed  Month  Weekday  Hour  Rentals  
FormattedDate                                                      
2014-12-31 23:00:00            1.8     12        3    23      3.0  
2015-01-01 00:00:00            1.6      1        4     0      9.0  
2015-01-01 01:00:00            1.3      1        4     1     15.0  
2015-01-01 02:00:00            1.2      1        4     2     19.0  
2015-01-01 03:00:00            1.0      1        4     3     13.0

In [4]:
df.describe()

Temperature  TotalCloudCover  PrecipitationHeight  MeanWindSpeed  \
count  17545.000000     17545.000000         17545.000000   17545.000000   
mean      11.375611         5.371445             0.061670       3.404087   
std        7.857857         2.622536             0.429316       2.121874   
min       -7.200000        -1.000000             0.000000       0.000000   
25%        5.100000         3.000000             0.000000       1.800000   
50%       10.800000         7.000000             0.000000       2.900000   
75%       16.900000         7.000000             0.000000       4.500000   
max       38.100000         8.000000            19.100000      18.800000   

              Month       Weekday          Hour       Rentals  
count  17545.000000  17545.000000  17545.000000  17545.000000  
mean       6.520148      3.008207     11.500655     69.642177  
std        3.449799      2.000667      6.922731     66.839148  
min        1.000000      0.000000      0.000000      0.000000  
25%        4.000000      1.000000      6.000000     18.000000  
50%        7.000000      3.000000     12.000000     50.000000  
75%       10.000000      5.000000     18.000000    101.000000  
max       12.000000      6.000000     23.000000    478.000000

In [5]:
#classic cross-validation test
x_train, x_test, y_train, y_test = train_test_split(df[['Temperature','PrecipitationHeight','TotalCloudCover','MeanWindSpeed','Month','Weekday','Hour']], df[['Rentals']], test_size=0.3)

In [6]:
reg = linear_model.LinearRegression()
reg.fit(x_train,y_train)
print(reg.coef_)
print(reg.intercept_)

[[ 3.84999537 -6.9786064  -1.02914604  0.71505008 -0.58005486  1.16532816
   1.13542757]]
[15.73004065]


In [7]:
y_pred = reg.predict(x_test)
print(np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

59.16196078097576


In [8]:
x_test

Temperature  PrecipitationHeight  TotalCloudCover  \
FormattedDate                                                            
2015-03-11 21:00:00          0.9                  0.0                0   
2015-02-17 11:00:00          2.5                  0.0                8   
2015-08-17 01:00:00         15.3                  0.0                7   
2016-11-30 11:00:00         -0.1                  0.0                6   
2016-08-06 20:00:00         16.8                  0.0                1   
...                          ...                  ...              ...   
2015-12-07 05:00:00          6.1                  0.0                6   
2016-01-17 03:00:00          0.2                  0.0                5   
2016-11-16 19:00:00          9.6                  0.0                8   
2016-02-04 21:00:00          4.8                  0.0                3   
2015-07-23 06:00:00         19.2                  0.0                7   

                     MeanWindSpeed  Month  Weekday  Hour  
FormattedDate                                             
2015-03-11 21:00:00            0.6      3        3    21  
2015-02-17 11:00:00            2.6      2        2    11  
2015-08-17 01:00:00            4.6      8        1     1  
2016-11-30 11:00:00            4.1     11        3    11  
2016-08-06 20:00:00            1.7      8        6    20  
...                            ...    ...      ...   ...  
2015-12-07 05:00:00            0.8     12        1     5  
2016-01-17 03:00:00            3.3      1        0     3  
2016-11-16 19:00:00            5.5     11        3    19  
2016-02-04 21:00:00            3.3      2        4    21  
2015-07-23 06:00:00            4.5      7        4     6  

[5264 rows x 7 columns]

In [9]:
#Predictions = x_test
#Predictions['Actual']=y_test
#Predictions['Prediction']=y_pred
#Predictions.head(20)

In [10]:
x_test

Temperature  PrecipitationHeight  TotalCloudCover  \
FormattedDate                                                            
2015-03-11 21:00:00          0.9                  0.0                0   
2015-02-17 11:00:00          2.5                  0.0                8   
2015-08-17 01:00:00         15.3                  0.0                7   
2016-11-30 11:00:00         -0.1                  0.0                6   
2016-08-06 20:00:00         16.8                  0.0                1   
...                          ...                  ...              ...   
2015-12-07 05:00:00          6.1                  0.0                6   
2016-01-17 03:00:00          0.2                  0.0                5   
2016-11-16 19:00:00          9.6                  0.0                8   
2016-02-04 21:00:00          4.8                  0.0                3   
2015-07-23 06:00:00         19.2                  0.0                7   

                     MeanWindSpeed  Month  Weekday  Hour  
FormattedDate                                             
2015-03-11 21:00:00            0.6      3        3    21  
2015-02-17 11:00:00            2.6      2        2    11  
2015-08-17 01:00:00            4.6      8        1     1  
2016-11-30 11:00:00            4.1     11        3    11  
2016-08-06 20:00:00            1.7      8        6    20  
...                            ...    ...      ...   ...  
2015-12-07 05:00:00            0.8     12        1     5  
2016-01-17 03:00:00            3.3      1        0     3  
2016-11-16 19:00:00            5.5     11        3    19  
2016-02-04 21:00:00            3.3      2        4    21  
2015-07-23 06:00:00            4.5      7        4     6  

[5264 rows x 7 columns]

In [11]:
y_pred_train = reg.predict(x_train)
print(np.sqrt(metrics.mean_squared_error(y_train, y_pred_train)))

57.09316544904048


In [12]:
#ns Linear Regression model with all parameters shows bad performance
#ns This is due to the fact, that not all parameters are actually linear.
#ns For comparison: Training one model with only linear parameters (temperature & precipitation).

#classic cross-validation testset
x_train_lin, x_test_lin, y_train_lin, y_test_lin = train_test_split(df[['Temperature','PrecipitationHeight']], df[['Rentals']], test_size=0.3)

reg_lin = linear_model.LinearRegression()
reg_lin.fit(x_train_lin,y_train_lin)
print(reg_lin.coef_)
print(reg_lin.intercept_)

[[ 4.1215358 -8.1085591]]
[23.12880252]


In [13]:
y_pred_lin = reg_lin.predict(x_test_lin)
print(np.sqrt(metrics.mean_squared_error(y_test_lin, y_pred_lin)))

57.77473171990919


In [14]:
#ns Performance has not really improved. Therefore linear models can be discarded. Also indication that these weather features are not sufficient to predict the bike rental behaviour.

## KFold Analysis

In [15]:
# KFold

#ns creating an array containing the implicit index, with the size of the specified dataframe df
split_index = np.arange(0,len(df),1)

#ns creating the KFold object, n_splits decideds the number of splits to be made, shuffle, decides on whether the splits are in order or random
kf = KFold(n_splits=8, shuffle=True)
kf.get_n_splits(split_index)

#ns iteration through all splits that are available, every interaction needs to be done in this iteration
for train_index, test_index in kf.split(split_index):
    print(train_index, test_index)

[    0     1     2 ... 17541 17543 17544] [    7    16    49 ... 17523 17529 17542]
[    0     1     2 ... 17542 17543 17544] [   13    17    18 ... 17510 17539 17541]
[    0     1     4 ... 17542 17543 17544] [    2     3     6 ... 17518 17525 17533]
[    0     1     2 ... 17540 17541 17542] [    5     8    21 ... 17527 17543 17544]
[    0     1     2 ... 17542 17543 17544] [   12    25    28 ... 17517 17524 17531]
[    0     2     3 ... 17542 17543 17544] [    1    15    24 ... 17508 17522 17528]
[    1     2     3 ... 17542 17543 17544] [    0     4    19 ... 17535 17538 17540]
[    0     1     2 ... 17542 17543 17544] [    9    11    22 ... 17534 17536 17537]


## Polynomial Approach

In [29]:
def polynomialregression(deg):
    xtrain_array = np.array(x_train)
    xtest_array = np.array(x_test)
    ytrain_array = np.array(y_train)
    ytest_array = np.array(y_test)
    
    poly = PolynomialFeatures(degree = deg, include_bias=False)
    poly_xtrain = poly.fit_transform(xtrain_array)
    
    
    poly_model = linear_model.LinearRegression()
    poly_model.fit(poly_xtrain, ytrain_array)
    
    y_train_predicted = poly_model.predict(poly_xtrain)
    
    poly1 = PolynomialFeatures(degree = deg, include_bias=False)
    poly_xtest = poly1.fit_transform(xtest_array)
    y_test_predicted = poly_model.predict(poly_xtest)
    
    #evaluating train
    rmse_train = np.sqrt(metrics.mean_squared_error(ytrain_array, y_train_predicted))
    r2_train = metrics.r2_score(ytrain_array, y_train_predicted)
    
    # evaluating test
    rmse_test = np.sqrt(metrics.mean_squared_error(ytest_array, y_test_predicted))
    r2_test = metrics.r2_score(ytest_array, y_test_predicted)
    
    print("Testing the polynomial function of degree {}".format(deg))
    
    print("\n")
    
    print("The model performance for the training set")
    print("-------------------------------------------")
    print("RMSE of training set is {}".format(rmse_train))
    print("R2 score of training set is {}".format(r2_train))
    
    print("\n")
    
    print("The model performance for the test set")
    print("-------------------------------------------")
    print("RMSE of test set is {}".format(rmse_test))
    print("R2 score of test set is {}".format(r2_test))
    
    print("\n")
    print("\n")

In [30]:
degr = [1,2,3,4]

for d in degr:
    polynomialregression(d)
    

Testing the polynomial function of degree 1


The model performance for the training set
-------------------------------------------
RMSE of training set is 57.09316544904049
R2 score of training set is 0.2478757581615958


The model performance for the test set
-------------------------------------------
RMSE of test set is 59.161960780975775
R2 score of test set is 0.266218886800466




Testing the polynomial function of degree 2


The model performance for the training set
-------------------------------------------
RMSE of training set is 47.907483422708424
R2 score of training set is 0.47042428934197567


The model performance for the test set
-------------------------------------------
RMSE of test set is 50.160541160242055
R2 score of test set is 0.4725201945237647




Testing the polynomial function of degree 3


The model performance for the training set
-------------------------------------------
RMSE of training set is 45.96982967307922
R2 score of training set is 0.51239614

In [50]:
def polynomialregression_lasso(deg, reg_par, x_train_inp, x_test_inp, y_train_inp, y_test_inp):
    xtrain_array = np.array(x_train_inp)
    xtest_array = np.array(x_test_inp)
    ytrain_array = np.array(y_train_inp)
    ytest_array = np.array(y_test_inp)
    
    poly = PolynomialFeatures(degree = deg, include_bias=False)
    poly_xtrain = poly.fit_transform(xtrain_array)
    
    #ns Training the model
    poly_model_L1 = linear_model.Lasso(alpha = reg_par, normalize=False)
    poly_model_L1.fit(poly_xtrain, ytrain_array)
    
    y_train_predicted = poly_model_L1.predict(poly_xtrain)
    
    poly1 = PolynomialFeatures(degree = deg, include_bias=False)
    poly_xtest = poly1.fit_transform(xtest_array)
    y_test_predicted = poly_model_L1.predict(poly_xtest)
    
    #evaluating train
    rmse_train = np.sqrt(metrics.mean_squared_error(ytrain_array, y_train_predicted))
    r2_train = metrics.r2_score(ytrain_array, y_train_predicted)
    
    # evaluating test
    rmse_test = np.sqrt(metrics.mean_squared_error(ytest_array, y_test_predicted))
    r2_test = metrics.r2_score(ytest_array, y_test_predicted)
    
    print("Testing the polynomial function with LASSO regularization of degree {}".format(deg))
    
    print("\n")
    
    print("The model performance for the training set")
    print("-------------------------------------------")
    print("RMSE of training set is {}".format(rmse_train))
    print("R2 score of training set is {}".format(r2_train))
    
    print("\n")
    
    print("The model performance for the test set")
    print("-------------------------------------------")
    print("RMSE of test set is {}".format(rmse_test))
    print("R2 score of test set is {}".format(r2_test))
    
    print("\n")
    print("\n")

In [52]:
degr = [1,2,3,4,5,6,7]

for d in degr:
    polynomialregression_lasso(d, 0.1, x_train, x_test, y_train, y_test)

Testing the polynomial function with LASSO regularization of degree 1


The model performance for the training set
-------------------------------------------
RMSE of training set is 57.09367187499033
R2 score of training set is 0.24786241516616447


The model performance for the test set
-------------------------------------------
RMSE of test set is 59.17152426004092
R2 score of test set is 0.2659816374798478




Testing the polynomial function with LASSO regularization of degree 2


The model performance for the training set
-------------------------------------------
RMSE of training set is 47.93835472027559
R2 score of training set is 0.4697415585584406


The model performance for the test set
-------------------------------------------
RMSE of test set is 50.18100177494655
R2 score of test set is 0.4720897860005959




Testing the polynomial function with LASSO regularization of degree 3


The model performance for the training set
-------------------------------------------
RMSE

In [44]:
"""ns Normalizing the initial dataframe for later regression"""

normalized_df = df

normalized_df['Temperature'] = np.divide(np.subtract(normalized_df['Temperature'],normalized_df['Temperature'].mean()),normalized_df['Temperature'].std())
normalized_df['PrecipitationHeight'] = np.divide(np.subtract(normalized_df['PrecipitationHeight'],normalized_df['PrecipitationHeight'].mean()),normalized_df['PrecipitationHeight'].std())
normalized_df['TotalCloudCover'] = np.divide(np.subtract(normalized_df['TotalCloudCover'],normalized_df['TotalCloudCover'].mean()),normalized_df['TotalCloudCover'].std())
normalized_df['MeanWindSpeed'] = np.divide(np.subtract(normalized_df['MeanWindSpeed'],normalized_df['MeanWindSpeed'].mean()),normalized_df['MeanWindSpeed'].std())
normalized_df['Month'] = np.divide(np.subtract(normalized_df['Month'],normalized_df['Month'].mean()),normalized_df['Month'].std())
normalized_df['Weekday'] = np.divide(np.subtract(normalized_df['Weekday'],normalized_df['Weekday'].mean()),normalized_df['Weekday'].std())
normalized_df['Hour'] = np.divide(np.subtract(normalized_df['Hour'],normalized_df['Hour'].mean()),normalized_df['Hour'].std())

In [45]:
#classic cross-validation test
x_train_norm, x_test_norm, y_train_norm, y_test_norm = train_test_split(normalized_df[['Temperature','PrecipitationHeight','TotalCloudCover','MeanWindSpeed','Month','Weekday','Hour']], normalized_df[['Rentals']], test_size=0.3)

In [51]:
degr = [1,2,3,4,5,6,7]

for d in degr:
    polynomialregression_lasso(d, 0.1, x_train_norm, x_test_norm, y_train_norm, y_test_norm)

Testing the polynomial function with LASSO regularization of degree 1


The model performance for the training set
-------------------------------------------
RMSE of training set is 57.51139357459657
R2 score of training set is 0.2567439415085695


The model performance for the test set
-------------------------------------------
RMSE of test set is 58.16076846021177
R2 score of test set is 0.24937073235422258




Testing the polynomial function with LASSO regularization of degree 2


The model performance for the training set
-------------------------------------------
RMSE of training set is 48.24781100233428
R2 score of training set is 0.4768985739852196


The model performance for the test set
-------------------------------------------
RMSE of test set is 49.352849993944695
R2 score of test set is 0.4595074702592703




Testing the polynomial function with LASSO regularization of degree 3


The model performance for the training set
-------------------------------------------
RMS