In [2]:
import pandas as pd
from sklearn import linear_model
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import Lasso
from sklearn import metrics
import numpy as np

import warnings

warnings.filterwarnings('ignore');


In [3]:
df = pd.read_csv("DataBase_WeatherRentalAmount_UTC.csv", index_col='FormattedDate')

In [4]:
df.head()

Temperature  TotalCloudCover  PrecipitationHeight  \
FormattedDate                                                            
2014-12-31 23:00:00          1.2                8                  0.0   
2015-01-01 00:00:00          1.2                8                  0.0   
2015-01-01 01:00:00          1.1                8                  0.0   
2015-01-01 02:00:00          1.2               -1                  0.0   
2015-01-01 03:00:00          1.1               -1                  0.0   

                     MeanWindSpeed  Month  Weekday  Hour  Rentals  
FormattedDate                                                      
2014-12-31 23:00:00            1.8     12        3    23      3.0  
2015-01-01 00:00:00            1.6      1        4     0     11.0  
2015-01-01 01:00:00            1.3      1        4     1     15.0  
2015-01-01 02:00:00            1.2      1        4     2     20.0  
2015-01-01 03:00:00            1.0      1        4     3     16.0

In [5]:
df.describe()

Temperature  TotalCloudCover  PrecipitationHeight  MeanWindSpeed  \
count  17545.000000     17545.000000         17545.000000   17545.000000   
mean      11.375611         5.371445             0.061670       3.404087   
std        7.857857         2.622536             0.429316       2.121874   
min       -7.200000        -1.000000             0.000000       0.000000   
25%        5.100000         3.000000             0.000000       1.800000   
50%       10.800000         7.000000             0.000000       2.900000   
75%       16.900000         7.000000             0.000000       4.500000   
max       38.100000         8.000000            19.100000      18.800000   

              Month       Weekday          Hour       Rentals  
count  17545.000000  17545.000000  17545.000000  17545.000000  
mean       6.520148      3.008207     11.500655     81.587518  
std        3.449799      2.000667      6.922731     79.200292  
min        1.000000      0.000000      0.000000      0.000000  
25%        4.000000      1.000000      6.000000     21.000000  
50%        7.000000      3.000000     12.000000     59.000000  
75%       10.000000      5.000000     18.000000    117.000000  
max       12.000000      6.000000     23.000000    533.000000

In [6]:
#classic cross-validation test
x_train, x_test, y_train, y_test = train_test_split(df[['Temperature','PrecipitationHeight','TotalCloudCover','MeanWindSpeed','Month','Weekday','Hour']], df[['Rentals']], test_size=0.3)

In [7]:
reg = linear_model.LinearRegression()
reg.fit(x_train,y_train)
print(reg.coef_)
print(reg.intercept_)

[[  4.68348049 -12.13244374  -1.42014215   0.79146871   0.3615741
    1.55074958   1.36158042]]
[11.54607938]


In [8]:
y_pred = reg.predict(x_test)
print(np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

68.45994496029459


In [10]:
x_test

Temperature  PrecipitationHeight  TotalCloudCover  \
FormattedDate                                                            
2015-05-22 16:00:00         19.5                  0.0                3   
2015-09-09 08:00:00         15.6                  0.0                1   
2016-03-26 04:00:00          5.2                  0.0                8   
2015-07-19 12:00:00         26.7                  0.0                5   
2015-05-15 05:00:00         13.7                  0.0                7   
...                          ...                  ...              ...   
2015-03-21 15:00:00          8.6                  0.0                7   
2016-06-16 14:00:00         17.8                  0.0                8   
2015-10-08 20:00:00         14.1                  0.0                7   
2016-09-15 18:00:00         22.8                  0.0                7   
2015-02-11 17:00:00          3.1                  0.0                7   

                     MeanWindSpeed  Month  Weekday  Hour  
FormattedDate                                             
2015-05-22 16:00:00            2.0      5        5    16  
2015-09-09 08:00:00            3.7      9        3     8  
2016-03-26 04:00:00            1.4      3        6     4  
2015-07-19 12:00:00            5.4      7        0    12  
2015-05-15 05:00:00            2.3      5        5     5  
...                            ...    ...      ...   ...  
2015-03-21 15:00:00            2.2      3        6    15  
2016-06-16 14:00:00            1.1      6        4    14  
2015-10-08 20:00:00            2.0     10        4    20  
2016-09-15 18:00:00            5.1      9        4    18  
2015-02-11 17:00:00            2.0      2        3    17  

[5264 rows x 7 columns]

In [11]:
#Predictions = x_test
#Predictions['Actual']=y_test
#Predictions['Prediction']=y_pred
#Predictions.head(20)

In [12]:
x_test

Temperature  PrecipitationHeight  TotalCloudCover  \
FormattedDate                                                            
2015-05-22 16:00:00         19.5                  0.0                3   
2015-09-09 08:00:00         15.6                  0.0                1   
2016-03-26 04:00:00          5.2                  0.0                8   
2015-07-19 12:00:00         26.7                  0.0                5   
2015-05-15 05:00:00         13.7                  0.0                7   
...                          ...                  ...              ...   
2015-03-21 15:00:00          8.6                  0.0                7   
2016-06-16 14:00:00         17.8                  0.0                8   
2015-10-08 20:00:00         14.1                  0.0                7   
2016-09-15 18:00:00         22.8                  0.0                7   
2015-02-11 17:00:00          3.1                  0.0                7   

                     MeanWindSpeed  Month  Weekday  Hour  
FormattedDate                                             
2015-05-22 16:00:00            2.0      5        5    16  
2015-09-09 08:00:00            3.7      9        3     8  
2016-03-26 04:00:00            1.4      3        6     4  
2015-07-19 12:00:00            5.4      7        0    12  
2015-05-15 05:00:00            2.3      5        5     5  
...                            ...    ...      ...   ...  
2015-03-21 15:00:00            2.2      3        6    15  
2016-06-16 14:00:00            1.1      6        4    14  
2015-10-08 20:00:00            2.0     10        4    20  
2016-09-15 18:00:00            5.1      9        4    18  
2015-02-11 17:00:00            2.0      2        3    17  

[5264 rows x 7 columns]

In [13]:
y_pred_train = reg.predict(x_train)
print(np.sqrt(metrics.mean_squared_error(y_train, y_pred_train)))

67.85392233671477


In [14]:
#ns Linear Regression model with all parameters shows bad performance
#ns This is due to the fact, that not all parameters are actually linear.
#ns For comparison: Training one model with only linear parameters (temperature & precipitation).

#classic cross-validation testset
x_train_lin, x_test_lin, y_train_lin, y_test_lin = train_test_split(df[['Temperature','PrecipitationHeight']], df[['Rentals']], test_size=0.3)

reg_lin = linear_model.LinearRegression()
reg_lin.fit(x_train_lin,y_train_lin)
print(reg_lin.coef_)
print(reg_lin.intercept_)

[[ 4.93900101 -9.36021083]]
[26.11052192]


In [15]:
y_pred_lin = reg_lin.predict(x_test_lin)
print(np.sqrt(metrics.mean_squared_error(y_test_lin, y_pred_lin)))

68.00030424145955


In [16]:
#ns Performance has not really improved. Therefore linear models can be discarded. Also indication that these weather features are not sufficient to predict the bike rental behaviour.

## KFold Analysis

In [17]:
# KFold

#ns creating an array containing the implicit index, with the size of the specified dataframe df
split_index = np.arange(0,len(df),1)

#ns creating the KFold object, n_splits decideds the number of splits to be made, shuffle, decides on whether the splits are in order or random
kf = KFold(n_splits=8, shuffle=True)
kf.get_n_splits(split_index)

#ns iteration through all splits that are available, every interaction needs to be done in this iteration
for train_index, test_index in kf.split(split_index):
    print(train_index, test_index)

[    0     3     5 ... 17542 17543 17544] [    1     2     4 ... 17516 17523 17540]
[    0     1     2 ... 17542 17543 17544] [    8     9    18 ... 17504 17517 17535]
[    0     1     2 ... 17542 17543 17544] [   14    20    24 ... 17526 17529 17532]
[    1     2     3 ... 17541 17542 17544] [    0     6    29 ... 17533 17538 17543]
[    0     1     2 ... 17541 17542 17543] [    3    10    13 ... 17537 17539 17544]
[    0     1     2 ... 17542 17543 17544] [   26    30    37 ... 17520 17528 17536]
[    0     1     2 ... 17542 17543 17544] [    5    21    22 ... 17512 17524 17527]
[    0     1     2 ... 17540 17543 17544] [    7    11    42 ... 17534 17541 17542]


## Polynomial Approach

In [18]:
def polynomialregression(deg):
    xtrain_array = np.array(x_train)
    xtest_array = np.array(x_test)
    ytrain_array = np.array(y_train)
    ytest_array = np.array(y_test)
    
    poly = PolynomialFeatures(degree = deg, include_bias=False)
    poly_xtrain = poly.fit_transform(xtrain_array)
    
    
    poly_model = linear_model.LinearRegression()
    poly_model.fit(poly_xtrain, ytrain_array)
    
    y_train_predicted = poly_model.predict(poly_xtrain)
    
    poly1 = PolynomialFeatures(degree = deg, include_bias=False)
    poly_xtest = poly1.fit_transform(xtest_array)
    y_test_predicted = poly_model.predict(poly_xtest)
    
    #evaluating train
    rmse_train = np.sqrt(metrics.mean_squared_error(ytrain_array, y_train_predicted))
    r2_train = metrics.r2_score(ytrain_array, y_train_predicted)
    
    # evaluating test
    rmse_test = np.sqrt(metrics.mean_squared_error(ytest_array, y_test_predicted))
    r2_test = metrics.r2_score(ytest_array, y_test_predicted)
    
    print("Testing the polynomial function of degree {}".format(deg))
    
    print("\n")
    
    print("The model performance for the training set")
    print("-------------------------------------------")
    print("RMSE of training set is {}".format(rmse_train))
    print("R2 score of training set is {}".format(r2_train))
    
    print("\n")
    
    print("The model performance for the test set")
    print("-------------------------------------------")
    print("RMSE of test set is {}".format(rmse_test))
    print("R2 score of test set is {}".format(r2_test))
    
    print("\n")
    print("\n")

In [19]:
degr = [1,2,3,4]

for d in degr:
    polynomialregression(d)
    

Testing the polynomial function of degree 1


The model performance for the training set
-------------------------------------------
RMSE of training set is 67.85392233671476
R2 score of training set is 0.26631834035457524


The model performance for the test set
-------------------------------------------
RMSE of test set is 68.45994496029459
R2 score of test set is 0.25188561994387604




Testing the polynomial function of degree 2


The model performance for the training set
-------------------------------------------
RMSE of training set is 57.67971411635066
R2 score of training set is 0.46984367578345243


The model performance for the test set
-------------------------------------------
RMSE of test set is 58.430440552351556
R2 score of test set is 0.45502919998665603




Testing the polynomial function of degree 3


The model performance for the training set
-------------------------------------------
RMSE of training set is 54.8604562707439
R2 score of training set is 0.5204028

In [20]:
def polynomialregression_lasso(deg, reg_par, x_train_inp, x_test_inp, y_train_inp, y_test_inp):
    xtrain_array = np.array(x_train_inp)
    xtest_array = np.array(x_test_inp)
    ytrain_array = np.array(y_train_inp)
    ytest_array = np.array(y_test_inp)
    
    poly = PolynomialFeatures(degree = deg, include_bias=False)
    poly_xtrain = poly.fit_transform(xtrain_array)
    
    #ns Training the model
    poly_model_L1 = linear_model.Lasso(alpha = reg_par, normalize=False)
    poly_model_L1.fit(poly_xtrain, ytrain_array)
    
    y_train_predicted = poly_model_L1.predict(poly_xtrain)
    
    poly1 = PolynomialFeatures(degree = deg, include_bias=False)
    poly_xtest = poly1.fit_transform(xtest_array)
    y_test_predicted = poly_model_L1.predict(poly_xtest)
    
    #evaluating train
    rmse_train = np.sqrt(metrics.mean_squared_error(ytrain_array, y_train_predicted))
    r2_train = metrics.r2_score(ytrain_array, y_train_predicted)
    
    # evaluating test
    rmse_test = np.sqrt(metrics.mean_squared_error(ytest_array, y_test_predicted))
    r2_test = metrics.r2_score(ytest_array, y_test_predicted)
    
    print("Testing the polynomial function with LASSO regularization of degree {}".format(deg))
    
    print("\n")
    
    print("The model performance for the training set")
    print("-------------------------------------------")
    print("RMSE of training set is {}".format(rmse_train))
    print("R2 score of training set is {}".format(r2_train))
    
    print("\n")
    
    print("The model performance for the test set")
    print("-------------------------------------------")
    print("RMSE of test set is {}".format(rmse_test))
    print("R2 score of test set is {}".format(r2_test))
    
    print("\n")
    print("\n")

In [21]:
degr = [1,2,3,4,5,6,7]

for d in degr:
    polynomialregression_lasso(d, 0.1, x_train, x_test, y_train, y_test)

Testing the polynomial function with LASSO regularization of degree 1


The model performance for the training set
-------------------------------------------
RMSE of training set is 67.85442433080745
R2 score of training set is 0.2663074845275647


The model performance for the test set
-------------------------------------------
RMSE of test set is 68.4489796614663
R2 score of test set is 0.2521252532294288




Testing the polynomial function with LASSO regularization of degree 2


The model performance for the training set
-------------------------------------------
RMSE of training set is 57.73492841227932
R2 score of training set is 0.468828198535276


The model performance for the test set
-------------------------------------------
RMSE of test set is 58.286901211926825
R2 score of test set is 0.45770344531411244




Testing the polynomial function with LASSO regularization of degree 3


The model performance for the training set
-------------------------------------------
RMSE 

In [ ]:
# Ab hier: mehrere Normalization Ansätze; AUFPASSEN, welchen man ausführt 

In [44]:
"""ns Normalizing the initial dataframe for later regression"""

normalized_df = df

normalized_df['Temperature'] = np.divide(np.subtract(normalized_df['Temperature'],normalized_df['Temperature'].mean()),normalized_df['Temperature'].std())
normalized_df['PrecipitationHeight'] = np.divide(np.subtract(normalized_df['PrecipitationHeight'],normalized_df['PrecipitationHeight'].mean()),normalized_df['PrecipitationHeight'].std())
normalized_df['TotalCloudCover'] = np.divide(np.subtract(normalized_df['TotalCloudCover'],normalized_df['TotalCloudCover'].mean()),normalized_df['TotalCloudCover'].std())
normalized_df['MeanWindSpeed'] = np.divide(np.subtract(normalized_df['MeanWindSpeed'],normalized_df['MeanWindSpeed'].mean()),normalized_df['MeanWindSpeed'].std())
normalized_df['Month'] = np.divide(np.subtract(normalized_df['Month'],normalized_df['Month'].mean()),normalized_df['Month'].std())
normalized_df['Weekday'] = np.divide(np.subtract(normalized_df['Weekday'],normalized_df['Weekday'].mean()),normalized_df['Weekday'].std())
normalized_df['Hour'] = np.divide(np.subtract(normalized_df['Hour'],normalized_df['Hour'].mean()),normalized_df['Hour'].std())

In [28]:
#minmax scaler
#https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html
#https://www.geeksforgeeks.org/data-normalization-in-data-mining/

normalized_df = df
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
print(scaler.fit(normalized_df))
MinMaxScaler()
print(scaler.data_max_) #Die maximalwerte werden angezeigt
print(scaler.transform(normalized_df))
#print(scaler.transform([[2, 2]]))


MinMaxScaler(copy=True, feature_range=(0, 1))
[ 38.1   8.   19.1  18.8  12.    6.   23.  533. ]
[[0.18543046 1.         0.         ... 0.5        1.         0.00562852]
 [0.18543046 1.         0.         ... 0.66666667 0.         0.0206379 ]
 [0.18322296 1.         0.         ... 0.66666667 0.04347826 0.02814259]
 ...
 [0.07726269 1.         0.         ... 1.         0.91304348 0.0206379 ]
 [0.07726269 1.         0.         ... 1.         0.95652174 0.01313321]
 [0.07284768 1.         0.         ... 1.         1.         0.        ]]


In [31]:
#z-score scaler
#https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.zscore.html
from scipy import stats
normalized_df = df
stats.zscore(normalized_df)

array([[-1.29499705,  1.00232368, -0.14365119, ..., -0.00410248,
         1.66114678, -0.99229126],
       [-1.29499705,  1.00232368, -0.14365119, ...,  0.49574506,
        -1.66133614, -0.89127865],
       [-1.30772352,  1.00232368, -0.14365119, ...,  0.49574506,
        -1.51688037, -0.84077235],
       ...,
       [-1.91859452,  1.00232368, -0.14365119, ...,  1.49544014,
         1.37223522, -0.89127865],
       [-1.91859452,  1.00232368, -0.14365119, ...,  1.49544014,
         1.516691  , -0.94178495],
       [-1.94404748,  1.00232368, -0.14365119, ...,  1.49544014,
         1.66114678, -1.03017099]])

In [32]:
#classic cross-validation test
x_train_norm, x_test_norm, y_train_norm, y_test_norm = train_test_split(normalized_df[['Temperature','PrecipitationHeight','TotalCloudCover','MeanWindSpeed','Month','Weekday','Hour']], normalized_df[['Rentals']], test_size=0.3)

In [33]:
degr = [1,2,3,4,5,6,7]

for d in degr:
    polynomialregression_lasso(d, 0.1, x_train_norm, x_test_norm, y_train_norm, y_test_norm)

Testing the polynomial function with LASSO regularization of degree 1


The model performance for the training set
-------------------------------------------
RMSE of training set is 67.91094887310793
R2 score of training set is 0.26451090502413954


The model performance for the test set
-------------------------------------------
RMSE of test set is 68.30804948694067
R2 score of test set is 0.25658212482779996




Testing the polynomial function with LASSO regularization of degree 2


The model performance for the training set
-------------------------------------------
RMSE of training set is 58.05019848903185
R2 score of training set is 0.46259208467158686


The model performance for the test set
-------------------------------------------
RMSE of test set is 57.536988203819455
R2 score of test set is 0.4725473480669301




Testing the polynomial function with LASSO regularization of degree 3


The model performance for the training set
-------------------------------------------
R