In [37]:
import pandas as pd
from sklearn import linear_model
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import Lasso
from sklearn import metrics
import numpy as np

import warnings

warnings.filterwarnings('ignore');


In [38]:
df = pd.read_csv("DataBase_WeatherRentalAmount_UTC.csv", index_col='FormattedDate')

In [39]:
df.head()

Temperature  TotalCloudCover  PrecipitationHeight  \
FormattedDate                                                            
2014-12-31 23:00:00          1.2                8                  0.0   
2015-01-01 00:00:00          1.2                8                  0.0   
2015-01-01 01:00:00          1.1                8                  0.0   
2015-01-01 02:00:00          1.2               -1                  0.0   
2015-01-01 03:00:00          1.1               -1                  0.0   

                     MeanWindSpeed  Month  Weekday  Hour  Rentals  
FormattedDate                                                      
2014-12-31 23:00:00            1.8     12        3    23      3.0  
2015-01-01 00:00:00            1.6      1        4     0      9.0  
2015-01-01 01:00:00            1.3      1        4     1     15.0  
2015-01-01 02:00:00            1.2      1        4     2     19.0  
2015-01-01 03:00:00            1.0      1        4     3     13.0

In [40]:
df.describe()

Temperature  TotalCloudCover  PrecipitationHeight  MeanWindSpeed  \
count  17544.000000     17544.000000         17544.000000   17544.000000   
mean      11.376482         5.371295             0.061674       3.404195   
std        7.857234         2.622536             0.429328       2.121886   
min       -7.200000        -1.000000             0.000000       0.000000   
25%        5.100000         3.000000             0.000000       1.800000   
50%       10.800000         7.000000             0.000000       2.900000   
75%       16.900000         7.000000             0.000000       4.500000   
max       38.100000         8.000000            19.100000      18.800000   

              Month       Weekday          Hour       Rentals  
count  17544.000000  17544.000000  17544.000000  17544.000000  
mean       6.519836      3.008037     11.500000     69.646147  
std        3.449649      2.000597      6.922384     66.838985  
min        1.000000      0.000000      0.000000      0.000000  
25%        4.000000      1.000000      5.750000     18.000000  
50%        7.000000      3.000000     11.500000     50.000000  
75%       10.000000      5.000000     17.250000    101.000000  
max       12.000000      6.000000     23.000000    478.000000

In [41]:
#classic cross-validation test
x_train, x_test, y_train, y_test = train_test_split(df[['Temperature','PrecipitationHeight','TotalCloudCover','MeanWindSpeed','Month','Weekday','Hour']], df[['Rentals']], test_size=0.3)

In [42]:
reg = linear_model.LinearRegression()
reg.fit(x_train,y_train)
print(reg.coef_)
print(reg.intercept_)

[[ 3.97759648 -7.3764003  -0.71402112  0.74563462 -0.58233401  1.33287429
   1.13967023]]
[12.57286183]


In [48]:
y_pred = reg.predict(x_test)
print("RSME: " + str(np.sqrt(metrics.mean_squared_error(y_test, y_pred))))
print("R^2: " + str(metrics.r2_score(y_test, y_pred)))

RSME: 57.2079329283452
R^2: 0.25106982590208937


In [10]:
x_test

Temperature  PrecipitationHeight  TotalCloudCover  \
FormattedDate                                                            
2015-05-22 16:00:00         19.5                  0.0                3   
2015-09-09 08:00:00         15.6                  0.0                1   
2016-03-26 04:00:00          5.2                  0.0                8   
2015-07-19 12:00:00         26.7                  0.0                5   
2015-05-15 05:00:00         13.7                  0.0                7   
...                          ...                  ...              ...   
2015-03-21 15:00:00          8.6                  0.0                7   
2016-06-16 14:00:00         17.8                  0.0                8   
2015-10-08 20:00:00         14.1                  0.0                7   
2016-09-15 18:00:00         22.8                  0.0                7   
2015-02-11 17:00:00          3.1                  0.0                7   

                     MeanWindSpeed  Month  Weekday  Hour  
FormattedDate                                             
2015-05-22 16:00:00            2.0      5        5    16  
2015-09-09 08:00:00            3.7      9        3     8  
2016-03-26 04:00:00            1.4      3        6     4  
2015-07-19 12:00:00            5.4      7        0    12  
2015-05-15 05:00:00            2.3      5        5     5  
...                            ...    ...      ...   ...  
2015-03-21 15:00:00            2.2      3        6    15  
2016-06-16 14:00:00            1.1      6        4    14  
2015-10-08 20:00:00            2.0     10        4    20  
2016-09-15 18:00:00            5.1      9        4    18  
2015-02-11 17:00:00            2.0      2        3    17  

[5264 rows x 7 columns]

In [11]:
#Predictions = x_test
#Predictions['Actual']=y_test
#Predictions['Prediction']=y_pred
#Predictions.head(20)

In [12]:
x_test

Temperature  PrecipitationHeight  TotalCloudCover  \
FormattedDate                                                            
2015-05-22 16:00:00         19.5                  0.0                3   
2015-09-09 08:00:00         15.6                  0.0                1   
2016-03-26 04:00:00          5.2                  0.0                8   
2015-07-19 12:00:00         26.7                  0.0                5   
2015-05-15 05:00:00         13.7                  0.0                7   
...                          ...                  ...              ...   
2015-03-21 15:00:00          8.6                  0.0                7   
2016-06-16 14:00:00         17.8                  0.0                8   
2015-10-08 20:00:00         14.1                  0.0                7   
2016-09-15 18:00:00         22.8                  0.0                7   
2015-02-11 17:00:00          3.1                  0.0                7   

                     MeanWindSpeed  Month  Weekday  Hour  
FormattedDate                                             
2015-05-22 16:00:00            2.0      5        5    16  
2015-09-09 08:00:00            3.7      9        3     8  
2016-03-26 04:00:00            1.4      3        6     4  
2015-07-19 12:00:00            5.4      7        0    12  
2015-05-15 05:00:00            2.3      5        5     5  
...                            ...    ...      ...   ...  
2015-03-21 15:00:00            2.2      3        6    15  
2016-06-16 14:00:00            1.1      6        4    14  
2015-10-08 20:00:00            2.0     10        4    20  
2016-09-15 18:00:00            5.1      9        4    18  
2015-02-11 17:00:00            2.0      2        3    17  

[5264 rows x 7 columns]

In [13]:
y_pred_train = reg.predict(x_train)
print(np.sqrt(metrics.mean_squared_error(y_train, y_pred_train)))

67.85392233671477


In [14]:
#ns Linear Regression model with all parameters shows bad performance
#ns This is due to the fact, that not all parameters are actually linear.
#ns For comparison: Training one model with only linear parameters (temperature & precipitation).

#classic cross-validation testset
x_train_lin, x_test_lin, y_train_lin, y_test_lin = train_test_split(df[['Temperature','PrecipitationHeight']], df[['Rentals']], test_size=0.3)

reg_lin = linear_model.LinearRegression()
reg_lin.fit(x_train_lin,y_train_lin)
print(reg_lin.coef_)
print(reg_lin.intercept_)

[[ 4.93900101 -9.36021083]]
[26.11052192]


In [15]:
y_pred_lin = reg_lin.predict(x_test_lin)
print(np.sqrt(metrics.mean_squared_error(y_test_lin, y_pred_lin)))

68.00030424145955


In [16]:
#ns Performance has not really improved. Therefore linear models can be discarded. Also indication that these weather features are not sufficient to predict the bike rental behaviour.

## KFold Analysis

In [17]:
# KFold

#ns creating an array containing the implicit index, with the size of the specified dataframe df
split_index = np.arange(0,len(df),1)

#ns creating the KFold object, n_splits decideds the number of splits to be made, shuffle, decides on whether the splits are in order or random
kf = KFold(n_splits=8, shuffle=True)
kf.get_n_splits(split_index)

#ns iteration through all splits that are available, every interaction needs to be done in this iteration
for train_index, test_index in kf.split(split_index):
    print(train_index, test_index)

[    0     3     5 ... 17542 17543 17544] [    1     2     4 ... 17516 17523 17540]
[    0     1     2 ... 17542 17543 17544] [    8     9    18 ... 17504 17517 17535]
[    0     1     2 ... 17542 17543 17544] [   14    20    24 ... 17526 17529 17532]
[    1     2     3 ... 17541 17542 17544] [    0     6    29 ... 17533 17538 17543]
[    0     1     2 ... 17541 17542 17543] [    3    10    13 ... 17537 17539 17544]
[    0     1     2 ... 17542 17543 17544] [   26    30    37 ... 17520 17528 17536]
[    0     1     2 ... 17542 17543 17544] [    5    21    22 ... 17512 17524 17527]
[    0     1     2 ... 17540 17543 17544] [    7    11    42 ... 17534 17541 17542]


## Polynomial Approach

In [51]:
def polynomialregression(deg, xtr, xte, ytr, yte):
    xtrain_array = np.array(xtr)
    xtest_array = np.array(xte)
    ytrain_array = np.array(ytr)
    ytest_array = np.array(yte)
    
    poly = PolynomialFeatures(degree = deg, include_bias=False)
    poly_xtrain = poly.fit_transform(xtrain_array)
    
    
    poly_model = linear_model.LinearRegression()
    poly_model.fit(poly_xtrain, ytrain_array)
    
    y_train_predicted = poly_model.predict(poly_xtrain)
    
    poly1 = PolynomialFeatures(degree = deg, include_bias=False)
    poly_xtest = poly1.fit_transform(xtest_array)
    y_test_predicted = poly_model.predict(poly_xtest)
    
    #evaluating train
    rmse_train = np.sqrt(metrics.mean_squared_error(ytrain_array, y_train_predicted))
    r2_train = metrics.r2_score(ytrain_array, y_train_predicted)
    
    # evaluating test
    rmse_test = np.sqrt(metrics.mean_squared_error(ytest_array, y_test_predicted))
    r2_test = metrics.r2_score(ytest_array, y_test_predicted)
    
    print("Testing the polynomial function of degree {}".format(deg))
    
    print("\n")
    
    print("The model performance for the training set")
    print("-------------------------------------------")
    print("RMSE of training set is {}".format(rmse_train))
    print("R2 score of training set is {}".format(r2_train))
    
    print("\n")
    
    print("The model performance for the test set")
    print("-------------------------------------------")
    print("RMSE of test set is {}".format(rmse_test))
    print("R2 score of test set is {}".format(r2_test))
    
    print("\n")
    print("\n")

In [19]:
degr = [1,2,3,4]

for d in degr:
    polynomialregression(d)
    

Testing the polynomial function of degree 1


The model performance for the training set
-------------------------------------------
RMSE of training set is 67.85392233671476
R2 score of training set is 0.26631834035457524


The model performance for the test set
-------------------------------------------
RMSE of test set is 68.45994496029459
R2 score of test set is 0.25188561994387604




Testing the polynomial function of degree 2


The model performance for the training set
-------------------------------------------
RMSE of training set is 57.67971411635066
R2 score of training set is 0.46984367578345243


The model performance for the test set
-------------------------------------------
RMSE of test set is 58.430440552351556
R2 score of test set is 0.45502919998665603




Testing the polynomial function of degree 3


The model performance for the training set
-------------------------------------------
RMSE of training set is 54.8604562707439
R2 score of training set is 0.5204028

In [52]:
def polynomialregression_lasso(deg, reg_par, x_train_inp, x_test_inp, y_train_inp, y_test_inp):
    xtrain_array = np.array(x_train_inp)
    xtest_array = np.array(x_test_inp)
    ytrain_array = np.array(y_train_inp)
    ytest_array = np.array(y_test_inp)
    
    poly = PolynomialFeatures(degree = deg, include_bias=False)
    poly_xtrain = poly.fit_transform(xtrain_array)
    
    #ns Training the model
    poly_model_L1 = linear_model.Lasso(alpha = reg_par, normalize=False)
    poly_model_L1.fit(poly_xtrain, ytrain_array)
    
    y_train_predicted = poly_model_L1.predict(poly_xtrain)
    
    poly1 = PolynomialFeatures(degree = deg, include_bias=False)
    poly_xtest = poly1.fit_transform(xtest_array)
    y_test_predicted = poly_model_L1.predict(poly_xtest)
    
    #evaluating train
    rmse_train = np.sqrt(metrics.mean_squared_error(ytrain_array, y_train_predicted))
    r2_train = metrics.r2_score(ytrain_array, y_train_predicted)
    
    # evaluating test
    rmse_test = np.sqrt(metrics.mean_squared_error(ytest_array, y_test_predicted))
    r2_test = metrics.r2_score(ytest_array, y_test_predicted)
    
    print("Testing the polynomial function with LASSO regularization of degree {}".format(deg))
    
    print("\n")
    
    print("The model performance for the training set")
    print("-------------------------------------------")
    print("RMSE of training set is {}".format(rmse_train))
    print("R2 score of training set is {}".format(r2_train))
    
    print("\n")
    
    print("The model performance for the test set")
    print("-------------------------------------------")
    print("RMSE of test set is {}".format(rmse_test))
    print("R2 score of test set is {}".format(r2_test))
    
    print("\n")
    print("\n")

In [21]:
degr = [1,2,3,4,5,6,7]

for d in degr:
    polynomialregression_lasso(d, 0.1, x_train, x_test, y_train, y_test)

Testing the polynomial function with LASSO regularization of degree 1


The model performance for the training set
-------------------------------------------
RMSE of training set is 67.85442433080745
R2 score of training set is 0.2663074845275647


The model performance for the test set
-------------------------------------------
RMSE of test set is 68.4489796614663
R2 score of test set is 0.2521252532294288




Testing the polynomial function with LASSO regularization of degree 2


The model performance for the training set
-------------------------------------------
RMSE of training set is 57.73492841227932
R2 score of training set is 0.468828198535276


The model performance for the test set
-------------------------------------------
RMSE of test set is 58.286901211926825
R2 score of test set is 0.45770344531411244




Testing the polynomial function with LASSO regularization of degree 3


The model performance for the training set
-------------------------------------------
RMSE 

In [ ]:
# Ab hier: mehrere Normalization Ansätze; AUFPASSEN, welchen man ausführt 

In [44]:
"""ns Normalizing the initial dataframe for later regression"""

normalized_df = df

normalized_df['Temperature'] = np.divide(np.subtract(normalized_df['Temperature'],normalized_df['Temperature'].mean()),normalized_df['Temperature'].std())
normalized_df['PrecipitationHeight'] = np.divide(np.subtract(normalized_df['PrecipitationHeight'],normalized_df['PrecipitationHeight'].mean()),normalized_df['PrecipitationHeight'].std())
normalized_df['TotalCloudCover'] = np.divide(np.subtract(normalized_df['TotalCloudCover'],normalized_df['TotalCloudCover'].mean()),normalized_df['TotalCloudCover'].std())
normalized_df['MeanWindSpeed'] = np.divide(np.subtract(normalized_df['MeanWindSpeed'],normalized_df['MeanWindSpeed'].mean()),normalized_df['MeanWindSpeed'].std())
normalized_df['Month'] = np.divide(np.subtract(normalized_df['Month'],normalized_df['Month'].mean()),normalized_df['Month'].std())
normalized_df['Weekday'] = np.divide(np.subtract(normalized_df['Weekday'],normalized_df['Weekday'].mean()),normalized_df['Weekday'].std())
normalized_df['Hour'] = np.divide(np.subtract(normalized_df['Hour'],normalized_df['Hour'].mean()),normalized_df['Hour'].std())

In [28]:
#minmax scaler
#https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html
#https://www.geeksforgeeks.org/data-normalization-in-data-mining/

normalized_df = df
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
print(scaler.fit(normalized_df))
MinMaxScaler()
print(scaler.data_max_) #Die maximalwerte werden angezeigt
print(scaler.transform(normalized_df))
#print(scaler.transform([[2, 2]]))


MinMaxScaler(copy=True, feature_range=(0, 1))
[ 38.1   8.   19.1  18.8  12.    6.   23.  533. ]
[[0.18543046 1.         0.         ... 0.5        1.         0.00562852]
 [0.18543046 1.         0.         ... 0.66666667 0.         0.0206379 ]
 [0.18322296 1.         0.         ... 0.66666667 0.04347826 0.02814259]
 ...
 [0.07726269 1.         0.         ... 1.         0.91304348 0.0206379 ]
 [0.07726269 1.         0.         ... 1.         0.95652174 0.01313321]
 [0.07284768 1.         0.         ... 1.         1.         0.        ]]


In [32]:
#classic cross-validation test
x_train_norm, x_test_norm, y_train_norm, y_test_norm = train_test_split(normalized_df[['Temperature','PrecipitationHeight','TotalCloudCover','MeanWindSpeed','Month','Weekday','Hour']], normalized_df[['Rentals']], test_size=0.3)

In [33]:
degr = [1,2,3,4,5,6,7]

for d in degr:
    polynomialregression_lasso(d, 0.1, x_train_norm, x_test_norm, y_train_norm, y_test_norm)

Testing the polynomial function with LASSO regularization of degree 1


The model performance for the training set
-------------------------------------------
RMSE of training set is 67.91094887310793
R2 score of training set is 0.26451090502413954


The model performance for the test set
-------------------------------------------
RMSE of test set is 68.30804948694067
R2 score of test set is 0.25658212482779996




Testing the polynomial function with LASSO regularization of degree 2


The model performance for the training set
-------------------------------------------
RMSE of training set is 58.05019848903185
R2 score of training set is 0.46259208467158686


The model performance for the test set
-------------------------------------------
RMSE of test set is 57.536988203819455
R2 score of test set is 0.4725473480669301




Testing the polynomial function with LASSO regularization of degree 3


The model performance for the training set
-------------------------------------------
R

## Prediction model for time frame aggregation

### 2h

In [16]:
df2 = pd.read_csv("DataBase_WeatherRentalAmount_2h_UTC.csv", index_col='grp')
df2.describe()

Temperature  TotalCloudCover  PrecipitationHeight  MeanWindSpeed  \
count  8772.000000      8772.000000          8772.000000    8772.000000   
mean     11.376482         5.371295             0.123347       3.404195   
std       7.839789         2.546550             0.733339       2.085740   
min      -7.050000        -1.000000             0.000000       0.000000   
25%       5.100000         3.500000             0.000000       1.850000   
50%      10.800000         6.500000             0.000000       2.900000   
75%      16.950000         7.000000             0.000000       4.500000   
max      37.950000         8.000000            32.500000      17.450000   

             Month      Weekday      Rentals  
count  8772.000000  8772.000000  8772.000000  
mean      6.519836     3.008037   139.367875  
std       3.448657     1.969271   128.817396  
min       1.000000     0.000000     0.000000  
25%       4.000000     1.000000    40.000000  
50%       7.000000     3.000000   103.000000  
75%      10.000000     5.000000   203.000000  
max      12.000000     6.000000   792.000000

In [32]:
#classic cross-validation test
x_train2, x_test2, y_train2, y_test2 = train_test_split(df2[['Temperature','TotalCloudCover','PrecipitationHeight','MeanWindSpeed','Month','Weekday']], df2[['Rentals']], test_size=0.3)

In [33]:
reg2 = linear_model.LinearRegression()
reg2.fit(x_train2,y_train2)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [49]:
y_pred2 = reg2.predict(x_test2)
print("RSME: " + str(np.sqrt(metrics.mean_squared_error(y_test2, y_pred2))))
print("R^2: " + str(metrics.r2_score(y_test2, y_pred2)))

RSME: 107.80754872326008
R^2: 0.2750004919807899


In [56]:
degr = [1,2,3,4,5,6,7]

for d in degr:
    polynomialregression(d, x_train2, x_test2, y_train2, y_test2)
    
for d in degr:
    polynomialregression_lasso(d, 0.1, x_train2, x_test2, y_train2, y_test2)
    

Testing the polynomial function of degree 1


The model performance for the training set
-------------------------------------------
RMSE of training set is 112.11625541009644
R2 score of training set is 0.2530985628098633


The model performance for the test set
-------------------------------------------
RMSE of test set is 107.80754872326008
R2 score of test set is 0.27500049198079013




Testing the polynomial function of degree 2


The model performance for the training set
-------------------------------------------
RMSE of training set is 106.38242498283714
R2 score of training set is 0.3275408640369558


The model performance for the test set
-------------------------------------------
RMSE of test set is 101.95881047070374
R2 score of test set is 0.35153149327555666




Testing the polynomial function of degree 3


The model performance for the training set
-------------------------------------------
RMSE of training set is 104.14548889397884
R2 score of training set is 0.3555

### 6h

In [57]:
df6 = pd.read_csv("DataBase_WeatherRentalAmount_6h_UTC.csv", index_col='grp')
df6.describe()

Temperature  TotalCloudCover  PrecipitationHeight  MeanWindSpeed  \
count  2924.000000      2924.000000          2924.000000    2924.000000   
mean     11.376482         5.371295             0.370041       3.404195   
std       7.720378         2.370696             1.490533       1.976931   
min      -6.150000        -1.000000             0.000000       0.200000   
25%       5.133333         3.666667             0.000000       1.933333   
50%      10.850000         6.166667             0.000000       2.883333   
75%      16.916667         7.166667             0.000000       4.433333   
max      36.433333         8.000000            38.100000      15.883333   

             Month      Weekday      Rentals  
count  2924.000000  2924.000000  2924.000000  
mean      6.519836     3.008037   418.388440  
std       3.448323     1.948290   342.948602  
min       1.000000     0.000000     0.000000  
25%       4.000000     1.000000   134.000000  
50%       7.000000     3.000000   345.500000  
75%      10.000000     5.000000   599.000000  
max      12.000000     6.000000  1706.000000

In [61]:
#classic cross-validation test
x_train6, x_test6, y_train6, y_test6 = train_test_split(df6[['Temperature','TotalCloudCover','PrecipitationHeight','MeanWindSpeed','Month','Weekday']], df6[['Rentals']], test_size=0.3)

In [67]:
reg6 = linear_model.LinearRegression()
reg6.fit(x_train6,y_train6)
y_pred6 = reg6.predict(x_test6)
print("RSME: " + str(np.sqrt(metrics.mean_squared_error(y_test6, y_pred6))))
print("R^2: " + str(metrics.r2_score(y_test6, y_pred6)))
print(reg6.coef_)

RSME: 284.2850662294068
R^2: 0.29713247094317297
[[ 24.08454093  -8.29995854 -21.59944897   5.91993102  -2.28015672
    7.71495382]]


In [63]:
degr = [1,2,3,4,5,6,7]

for d in degr:
    polynomialregression(d, x_train6, x_test6, y_train6, y_test6)
    
for d in degr:
    polynomialregression_lasso(d, 0.1, x_train6, x_test6, y_train6, y_test6)
    

Testing the polynomial function of degree 1


The model performance for the training set
-------------------------------------------
RMSE of training set is 283.64138122580454
R2 score of training set is 0.32206819188399627


The model performance for the test set
-------------------------------------------
RMSE of test set is 284.2850662294068
R2 score of test set is 0.29713247094317297




Testing the polynomial function of degree 2


The model performance for the training set
-------------------------------------------
RMSE of training set is 267.16566478552875
R2 score of training set is 0.39853810981185334


The model performance for the test set
-------------------------------------------
RMSE of test set is 277.28257364767245
R2 score of test set is 0.33133199945712233




Testing the polynomial function of degree 3


The model performance for the training set
-------------------------------------------
RMSE of training set is 257.74504207277386
R2 score of training set is 0.440

### 24h

In [68]:
df24 = pd.read_csv("DataBase_WeatherRentalAmount_24h_UTC.csv", index_col='grp')
df24.describe()

Temperature  TotalCloudCover  PrecipitationHeight  MeanWindSpeed  \
count   731.000000       731.000000           731.000000     731.000000   
mean     11.376482         5.371295             1.480164       3.404195   
std       7.247375         1.958596             3.556072       1.635631   
min      -5.683333         0.000000             0.000000       1.058333   
25%       5.318750         4.208333             0.000000       2.227083   
50%      10.941667         5.916667             0.000000       3.033333   
75%      17.004167         6.875000             1.100000       4.135417   
max      29.925000         8.000000            44.700000      10.650000   

            Month     Weekday      Rentals  
count  731.000000  731.000000   731.000000  
mean     6.519836    3.008037  1683.752340  
std      3.449820    1.941275   916.656171  
min      1.000000    0.250000     0.000000  
25%      3.979167    0.958333   967.727273  
50%      7.000000    2.958333  1559.000000  
75%      9.958333    4.958333  2094.086957  
max     12.000000    5.958333  4413.913043

In [69]:
#classic cross-validation test
x_train24, x_test24, y_train24, y_test24 = train_test_split(df24[['Temperature','TotalCloudCover','PrecipitationHeight','MeanWindSpeed','Month','Weekday']], df24[['Rentals']], test_size=0.3)

In [70]:
reg24 = linear_model.LinearRegression()
reg24.fit(x_train24,y_train24)
y_pred24 = reg24.predict(x_test24)
print("RSME: " + str(np.sqrt(metrics.mean_squared_error(y_test24, y_pred24))))
print("R^2: " + str(metrics.r2_score(y_test24, y_pred24)))
print(reg24.coef_)

RSME: 738.655673270964
R^2: 0.31813942078804003
[[ 78.18416888 -45.76021137 -23.12093727 -69.83881644 -11.28272445
   12.94096617]]


In [71]:
degr = [1,2,3,4,5,6,7]

for d in degr:
    polynomialregression(d, x_train24, x_test24, y_train24, y_test24)
    
for d in degr:
    polynomialregression_lasso(d, 0.1, x_train24, x_test24, y_train24, y_test24)
    

Testing the polynomial function of degree 1


The model performance for the training set
-------------------------------------------
RMSE of training set is 684.5003849880906
R2 score of training set is 0.4521451780293474


The model performance for the test set
-------------------------------------------
RMSE of test set is 738.655673270964
R2 score of test set is 0.31813942078804003




Testing the polynomial function of degree 2


The model performance for the training set
-------------------------------------------
RMSE of training set is 592.1647348487185
R2 score of training set is 0.5899817613963929


The model performance for the test set
-------------------------------------------
RMSE of test set is 614.7039426544269
R2 score of test set is 0.5277809482328346




Testing the polynomial function of degree 3


The model performance for the training set
-------------------------------------------
RMSE of training set is 548.0245794673655
R2 score of training set is 0.64882938356